### ISSUE TITLE
See the relynts of a lynt

### ISSUE THREAD

**Issue by MuratDev41** [Sylicium/lyntr-toolbox-script#1]
It is so annoying not being able to see who relynted my lynts

**Comment by Sylicium** [comment]
Im not sure to understand what feature do you want, could you please explain more in details what you woud expect in Lyntr+ ?

**Comment by meepstertron** [comment]
add the feature to see all the relynts in a list prob :P

**Comment by Sylicium** [comment]
I  just checked and Unfortunately, since this script is iser sided to modify DOM elements on the display, it won't be able to fetch all the relynts of a messages as there's nothing to get such list even with code..
It would need to modify the core app in order to add this feature, but thats not the purpose of Lyntr+. You may ask for the change (or do it yourself) here: https://github.com/face-hh/lyntr
